version: "3.9"
services:
  redis:
    container_name: "redis"
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - $PWD/configs/redis.conf:/usr/local/etc/redis/redis.conf
  server:
    container_name: API_server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    ports:
      - "127.0.0.1:80:80"
  database:
    container_name: PG_base
    image: postgres:14.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - ${PG_PORT}
      - "${PG_PORT}:${PG_PORT}"